<a href="https://colab.research.google.com/github/01fe21bec088/Python_for_ML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a=np.array([1,4,2,0,3])
print(a)
b=np.zeros(3)
print(b)
c=np.ones(3)
print(c)
d=np.sort(a)
print(d)

[1 4 2 0 3]
[0. 0. 0.]
[1. 1. 1.]
[0 1 2 3 4]
